# Generated by Django 5.2.16 on 2026-08-01 20:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='병원 UUID')),
                ('hospital_code', models.CharField(blank=True, help_text='공공데이터 또는 BrainOn 내부 병원 코드', max_length=30, null=True, unique=True, verbose_name='병원 코드')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='병원명')),
                ('address', models.TextField(blank=True, verbose_name='병원 주소')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='병원 전화번호')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='비활성 병원은 검색과 신규 의료진 가입에서 제외됩니다.', verbose_name='사용 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 일시')),
            ],
            options={
                'verbose_name': '병원',
                'verbose_name_plural': '병원',
                'db_table': 'hospitals',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['is_active', 'name'], name='hospital_active_name_idx')],
            },
        ),
    ]
