# Generated by Django 5.2.16 on 2026-08-01 23:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientFavoriteHospital',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 일시')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_patient_links', to='hospitals.hospital', verbose_name='찜한 병원')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_hospital_links', to='patients.patient', verbose_name='환자')),
            ],
            options={
                'verbose_name': '환자 찜 병원',
                'verbose_name_plural': '환자 찜 병원',
                'db_table': 'patient_favorite_hospitals',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['patient', 'created_at'], name='favhospital_patient_date_idx'), models.Index(fields=['hospital', 'created_at'], name='favhospital_hospital_date_idx')],
                'constraints': [models.UniqueConstraint(fields=('patient', 'hospital'), name='patient_favorite_hospital_uniq')],
            },
        ),
    ]
