# Generated by Django 5.2.16 on 2026-08-02 07:09

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0002_patientfavoritehospital'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='external_place_id',
            field=models.CharField(blank=True, default='', help_text='외부 API에서 부여한 병원 또는 장소 ID입니다.', max_length=255, verbose_name='외부 병원 식별자'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='external_provider',
            field=models.CharField(blank=True, db_index=True, default='', help_text='예: HIRA, KAKAO_LOCAL, NAVER_LOCAL', max_length=100, verbose_name='외부 데이터 제공자'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='external_synced_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='외부 데이터 동기화 일시'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='WGS84(EPSG:4326) 기준 위도입니다.', max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-90')), django.core.validators.MaxValueValidator(Decimal('90'))], verbose_name='위도'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='WGS84(EPSG:4326) 기준 경도입니다.', max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-180')), django.core.validators.MaxValueValidator(Decimal('180'))], verbose_name='경도'),
        ),
        migrations.AddIndex(
            model_name='hospital',
            index=models.Index(fields=['latitude', 'longitude'], name='hospital_coordinates_idx'),
        ),
        migrations.AddConstraint(
            model_name='hospital',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('latitude__isnull', True), ('longitude__isnull', True)), models.Q(('latitude__isnull', False), ('longitude__isnull', False)), _connector='OR'), name='hospital_coordinates_pair_valid'),
        ),
        migrations.AddConstraint(
            model_name='hospital',
            constraint=models.CheckConstraint(condition=models.Q(('latitude__isnull', True), models.Q(('latitude__gte', Decimal('-90')), ('latitude__lte', Decimal('90'))), _connector='OR'), name='hospital_latitude_range'),
        ),
        migrations.AddConstraint(
            model_name='hospital',
            constraint=models.CheckConstraint(condition=models.Q(('longitude__isnull', True), models.Q(('longitude__gte', Decimal('-180')), ('longitude__lte', Decimal('180'))), _connector='OR'), name='hospital_longitude_range'),
        ),
        migrations.AddConstraint(
            model_name='hospital',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('external_provider', ''), _negated=True), models.Q(('external_place_id', ''), _negated=True)), fields=('external_provider', 'external_place_id'), name='hospital_external_ref_uniq'),
        ),
    ]
