# Generated by Django 5.2.16 on 2026-08-04 02:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StoredObject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 일시')),
                ('provider', models.CharField(choices=[('GCS', 'Google Cloud Storage'), ('S3', 'Amazon S3 호환'), ('LOCAL', '로컬 스토리지')], db_index=True, default='GCS', max_length=16)),
                ('bucket_name', models.CharField(max_length=255)),
                ('object_key', models.CharField(max_length=1024)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=150)),
                ('file_format', models.CharField(blank=True, db_index=True, max_length=32)),
                ('file_size_bytes', models.PositiveBigIntegerField(default=0)),
                ('sha256', models.CharField(blank=True, db_index=True, max_length=64)),
                ('encryption_key_id', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('PENDING', '업로드 대기'), ('AVAILABLE', '사용 가능'), ('QUARANTINED', '격리'), ('DELETED', '삭제')], db_index=True, default='PENDING', max_length=16)),
                ('available_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_objects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='storedobj_status_date_idx'), models.Index(fields=['sha256', 'file_size_bytes'], name='storedobj_hash_size_idx')],
                'constraints': [models.UniqueConstraint(fields=('provider', 'bucket_name', 'object_key'), name='storedobj_location_uniq'), models.CheckConstraint(condition=models.Q(models.Q(('available_at__isnull', False), ('status', 'AVAILABLE')), models.Q(('status', 'AVAILABLE'), _negated=True), _connector='OR'), name='storedobj_available_at_req'), models.CheckConstraint(condition=models.Q(models.Q(('deleted_at__isnull', False), ('status', 'DELETED')), models.Q(('status', 'DELETED'), _negated=True), _connector='OR'), name='storedobj_deleted_at_req')],
            },
        ),
    ]
