# Generated by Django 5.2.16 on 2026-08-04 02:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0004_appointmentstatushistory_appointment_cancelled_by_and_more'),
        ('clinicians', '0002_clinicianavailability_cliniciantimeoff'),
        ('hospitals', '0003_hospital_external_place_id_and_more'),
        ('patients', '0004_provisional_identity_chart_trigger'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExaminationCatalog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 일시')),
                ('code', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('LABORATORY', '진단검사'), ('IMAGING', '영상검사'), ('PHYSIOLOGY', '생리기능검사'), ('PATHOLOGY', '병리검사'), ('NEURO_ASSESSMENT', '신경계 평가'), ('OTHER', '기타')], db_index=True, max_length=24)),
                ('specimen_type', models.CharField(blank=True, max_length=100)),
                ('default_unit', models.CharField(blank=True, max_length=40)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'ordering': ['category', 'name'],
                'constraints': [models.UniqueConstraint(fields=('category', 'code'), name='examcatalog_category_code_uniq')],
            },
        ),
        migrations.CreateModel(
            name='Examination',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 일시')),
                ('test_code', models.CharField(db_index=True, max_length=64)),
                ('test_name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('LABORATORY', '진단검사'), ('IMAGING', '영상검사'), ('PHYSIOLOGY', '생리기능검사'), ('PATHOLOGY', '병리검사'), ('NEURO_ASSESSMENT', '신경계 평가'), ('OTHER', '기타')], db_index=True, max_length=24)),
                ('accession_number', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('REGISTERED', '등록'), ('IN_PROGRESS', '검사 중'), ('PRELIMINARY', '예비 결과'), ('FINAL', '최종 결과'), ('CORRECTED', '정정'), ('CANCELLED', '취소')], db_index=True, default='REGISTERED', max_length=16)),
                ('source', models.CharField(choices=[('INTERNAL', '원내'), ('EXTERNAL', '외부 기관'), ('PATIENT_UPLOAD', '환자 업로드')], default='INTERNAL', max_length=24)),
                ('performed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('result_available_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('encounter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='examinations', to='appointments.encounter')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='examinations', to='hospitals.hospital')),
                ('ordered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordered_examinations', to='clinicians.clinician')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='examinations', to='patients.patient')),
                ('catalog', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='examinations', to='diagnostics.examinationcatalog')),
            ],
            options={
                'ordering': ['-performed_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExaminationObservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 일시')),
                ('code', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=200)),
                ('sequence', models.PositiveIntegerField(default=1)),
                ('value_type', models.CharField(choices=[('NUMERIC', '숫자'), ('TEXT', '문자'), ('CODED', '코드'), ('BOOLEAN', '참/거짓')], max_length=16)),
                ('numeric_value', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('text_value', models.TextField(blank=True)),
                ('coded_value', models.CharField(blank=True, max_length=100)),
                ('boolean_value', models.BooleanField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, max_length=40)),
                ('reference_low', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('reference_high', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('reference_text', models.CharField(blank=True, max_length=200)),
                ('interpretation', models.CharField(choices=[('NORMAL', '정상'), ('LOW', '낮음'), ('HIGH', '높음'), ('ABNORMAL', '이상'), ('CRITICAL', '위험'), ('UNKNOWN', '미판정')], db_index=True, default='UNKNOWN', max_length=16)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('examination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='diagnostics.examination')),
            ],
            options={
                'ordering': ['sequence', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='DiagnosticReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 일시')),
                ('status', models.CharField(choices=[('DRAFT', '작성 중'), ('FINAL', '최종'), ('CORRECTED', '정정'), ('CANCELLED', '취소')], db_index=True, default='DRAFT', max_length=16)),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField(blank=True)),
                ('conclusion', models.TextField(blank=True)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('is_released_to_patient', models.BooleanField(db_index=True, default=False)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diagnostic_reports', to='clinicians.clinician')),
                ('released_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='released_diagnostic_reports', to=settings.AUTH_USER_MODEL)),
                ('examination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='diagnostics.examination')),
            ],
            options={
                'ordering': ['-issued_at', '-created_at'],
                'indexes': [models.Index(fields=['examination', 'status'], name='diagreport_exam_status_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('is_released_to_patient', False), models.Q(('released_at__isnull', False), ('released_by__isnull', False), ('status__in', ['FINAL', 'CORRECTED'])), _connector='OR'), name='diagreport_release_valid')],
            },
        ),
        migrations.AddIndex(
            model_name='examination',
            index=models.Index(fields=['patient', 'performed_at'], name='exam_patient_performed_idx'),
        ),
        migrations.AddIndex(
            model_name='examination',
            index=models.Index(fields=['hospital', 'status'], name='exam_hospital_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='examination',
            constraint=models.UniqueConstraint(condition=models.Q(('accession_number', ''), _negated=True), fields=('hospital', 'accession_number'), name='exam_hospital_accession_uniq'),
        ),
        migrations.AddConstraint(
            model_name='examinationobservation',
            constraint=models.UniqueConstraint(fields=('examination', 'code', 'sequence'), name='examobs_exam_code_seq_uniq'),
        ),
        migrations.AddConstraint(
            model_name='examinationobservation',
            constraint=models.CheckConstraint(condition=models.Q(('reference_low__isnull', True), ('reference_high__isnull', True), ('reference_high__gte', models.F('reference_low')), _connector='OR'), name='examobs_reference_range_valid'),
        ),
    ]
