# Generated by Django 5.2.16 on 2026-08-04 03:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
        ('clinicians', '0002_clinicianavailability_cliniciantimeoff'),
        ('diagnostics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticReportAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 일시')),
                ('asset_type', models.CharField(choices=[('REPORT', '보고서'), ('PATIENT_COPY', '환자용 사본'), ('SOURCE', '검사 원본'), ('OTHER', '기타')], max_length=16)),
                ('display_name', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['asset_type', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='DiagnosticReportStatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 일시')),
                ('previous_status', models.CharField(blank=True, max_length=16)),
                ('new_status', models.CharField(choices=[('DRAFT', '작성 중'), ('FINAL', '최종'), ('CORRECTED', '정정'), ('CANCELLED', '취소')], max_length=16)),
                ('reason', models.TextField(blank=True)),
                ('is_released_to_patient', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExaminationStatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 일시')),
                ('previous_status', models.CharField(blank=True, max_length=16)),
                ('new_status', models.CharField(choices=[('REGISTERED', '등록'), ('IN_PROGRESS', '검사 중'), ('PRELIMINARY', '예비 결과'), ('FINAL', '최종 결과'), ('CORRECTED', '정정'), ('CANCELLED', '취소')], max_length=16)),
                ('reason', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='diagnosticreport',
            name='revision_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='diagnosticreport',
            name='signed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosticreport',
            name='signed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='signed_diagnostic_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='diagnosticreport',
            name='supersedes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='corrections', to='diagnostics.diagnosticreport'),
        ),
        migrations.AddConstraint(
            model_name='diagnosticreport',
            constraint=models.UniqueConstraint(fields=('examination', 'revision_number'), name='diagreport_exam_revision_uniq'),
        ),
        migrations.AddField(
            model_name='diagnosticreportasset',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='diagnostics.diagnosticreport'),
        ),
        migrations.AddField(
            model_name='diagnosticreportasset',
            name='stored_object',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='diagnostic_report_asset', to='assets.storedobject'),
        ),
        migrations.AddField(
            model_name='diagnosticreportstatushistory',
            name='changed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diagnostic_report_status_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='diagnosticreportstatushistory',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status_history', to='diagnostics.diagnosticreport'),
        ),
        migrations.AddField(
            model_name='examinationstatushistory',
            name='changed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='examination_status_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='examinationstatushistory',
            name='examination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status_history', to='diagnostics.examination'),
        ),
        migrations.AddIndex(
            model_name='diagnosticreportstatushistory',
            index=models.Index(fields=['report', 'created_at'], name='diagreporthist_report_idx'),
        ),
        migrations.AddIndex(
            model_name='examinationstatushistory',
            index=models.Index(fields=['examination', 'created_at'], name='examhist_exam_date_idx'),
        ),
    ]
