# Generated by Django 5.2.16 on 2026-08-01 22:51

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 일시')),
                ('platform', models.CharField(choices=[('ANDROID', 'Android'), ('IOS', 'iOS'), ('WEB', 'Web')], db_index=True, max_length=16, verbose_name='플랫폼')),
                ('fcm_token', models.CharField(max_length=512, unique=True, verbose_name='FCM 토큰')),
                ('device_name', models.CharField(blank=True, max_length=200, verbose_name='기기 이름')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='활성 여부')),
                ('registered_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='등록 일시')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='마지막 사용 일시')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '사용자 기기',
                'verbose_name_plural': '사용자 기기',
                'ordering': ['-last_used_at', '-registered_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='device_user_active_idx'), models.Index(fields=['platform', 'is_active'], name='device_platform_active_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('last_used_at__isnull', True), ('last_used_at__gte', models.F('registered_at')), _connector='OR'), name='device_last_used_after_reg')],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 일시')),
                ('type', models.CharField(choices=[('APPOINTMENT', '진료 예약'), ('MEDICATION', '복약'), ('TEST_RESULT', '검사 결과'), ('CONSULTATION', '협진'), ('EMERGENCY', '응급 안내'), ('SYSTEM', '시스템'), ('OTHER', '기타')], db_index=True, max_length=24, verbose_name='알림 유형')),
                ('title', models.CharField(max_length=200, verbose_name='알림 제목')),
                ('body', models.TextField(verbose_name='알림 내용')),
                ('data', models.JSONField(blank=True, default=dict, help_text='화면 이동 경로, 관련 객체 UUID 등의 추가 정보를 저장합니다.', verbose_name='추가 데이터')),
                ('is_read', models.BooleanField(db_index=True, default=False, verbose_name='읽음 여부')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='읽은 일시')),
                ('deduplication_key', models.CharField(blank=True, help_text='동일 알림의 중복 생성을 방지하는 키입니다.', max_length=255, null=True, verbose_name='중복 방지 키')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='수신 사용자')),
            ],
            options={
                'verbose_name': '알림',
                'verbose_name_plural': '알림',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read', 'created_at'], name='noti_rec_read_date_idx'), models.Index(fields=['type', 'created_at'], name='noti_type_date_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('is_read', False), ('read_at__isnull', True)), models.Q(('is_read', True), ('read_at__isnull', False)), _connector='OR'), name='notification_read_state_valid'), models.UniqueConstraint(condition=models.Q(('deduplication_key__isnull', False), models.Q(('deduplication_key', ''), _negated=True)), fields=('recipient', 'deduplication_key'), name='notification_rec_dedup_uniq')],
            },
        ),
    ]
