# Generated by Django 5.2.16 on 2026-08-03 07:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 일시')),
                ('notification_type', models.CharField(choices=[('APPOINTMENT', '진료 예약'), ('MEDICATION', '복약'), ('TEST_RESULT', '검사 결과'), ('CONSULTATION', '협진'), ('EMERGENCY', '응급 안내'), ('SYSTEM', '시스템'), ('OTHER', '기타')], max_length=24, verbose_name='알림 유형')),
                ('in_app_enabled', models.BooleanField(default=True, verbose_name='앱 내 알림 사용')),
                ('push_enabled', models.BooleanField(default=True, verbose_name='푸시 알림 사용')),
                ('email_enabled', models.BooleanField(default=False, verbose_name='이메일 알림 사용')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '알림 설정',
                'verbose_name_plural': '알림 설정',
                'ordering': ['user', 'notification_type'],
                'constraints': [models.UniqueConstraint(fields=('user', 'notification_type'), name='noti_pref_user_type_unique')],
            },
        ),
    ]
