# Generated by Django 5.2.16 on 2026-08-03 08:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notificationpreference'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationpreference',
            name='in_app_enabled',
        ),
        migrations.CreateModel(
            name='NotificationSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 일시')),
                ('quiet_hours_enabled', models.BooleanField(default=False, verbose_name='방해금지 사용')),
                ('quiet_hours_start', models.TimeField(blank=True, null=True, verbose_name='방해금지 시작 시간')),
                ('quiet_hours_end', models.TimeField(blank=True, null=True, verbose_name='방해금지 종료 시간')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_setting', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '공통 알림 설정',
                'verbose_name_plural': '공통 알림 설정',
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('quiet_hours_end__isnull', True), ('quiet_hours_start__isnull', True)), models.Q(('quiet_hours_end__isnull', False), ('quiet_hours_start__isnull', False)), _connector='OR'), name='noti_quiet_hours_pair_valid'), models.CheckConstraint(condition=models.Q(('quiet_hours_enabled', False), models.Q(('quiet_hours_end__isnull', False), ('quiet_hours_start__isnull', False)), _connector='OR'), name='noti_quiet_hours_required'), models.CheckConstraint(condition=models.Q(('quiet_hours_start__isnull', True), models.Q(('quiet_hours_start', models.F('quiet_hours_end')), _negated=True), _connector='OR'), name='noti_quiet_hours_different')],
            },
        ),
    ]
