# Generated by Django 5.2.16 on 2026-08-04 02:56

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_device_client_identity'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 일시')),
                ('channel', models.CharField(choices=[('PUSH', '푸시'), ('EMAIL', '이메일')], db_index=True, max_length=16)),
                ('destination', models.CharField(blank=True, max_length=512)),
                ('status', models.CharField(choices=[('PENDING', '전송 대기'), ('SUPPRESSED', '설정에 따라 보류'), ('SENDING', '전송 중'), ('SENT', '전송 완료'), ('DELIVERED', '수신 확인'), ('FAILED', '전송 실패'), ('CANCELLED', '취소')], db_index=True, default='PENDING', max_length=16)),
                ('provider_message_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('scheduled_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('next_attempt_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=100)),
                ('error_message', models.TextField(blank=True)),
                ('provider_response', models.JSONField(blank=True, default=dict)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_deliveries', to='notifications.device')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='notifications.notification')),
            ],
            options={
                'ordering': ['scheduled_at', 'created_at'],
                'indexes': [models.Index(fields=['status', 'next_attempt_at'], name='notidelivery_retry_idx'), models.Index(fields=['notification', 'channel'], name='notidelivery_noti_channel_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('channel', 'PUSH'), ('device__isnull', False)), models.Q(('channel', 'EMAIL'), ('device__isnull', True)), _connector='OR'), name='notidelivery_target_valid'), models.CheckConstraint(condition=models.Q(('delivered_at__isnull', True), models.Q(('delivered_at__gte', models.F('sent_at')), ('sent_at__isnull', False)), _connector='OR'), name='notidelivery_time_valid')],
            },
        ),
    ]
