# Generated by Django 5.2.16 on 2026-08-01 20:05

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CTCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 일시')),
                ('study_type', models.CharField(choices=[('NCCT', '비조영 뇌 CT'), ('CTA', 'CT 혈관조영'), ('CTP', 'CT 관류'), ('OTHER', '기타')], default='NCCT', max_length=16)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('UPLOADED', '업로드 완료'), ('VALIDATING', '검증 중'), ('READY', '추론 준비'), ('PROCESSING', '추론 중'), ('COMPLETED', '분석 완료'), ('FAILED', '실패'), ('ARCHIVED', '보관')], default='UPLOADED', max_length=16)),
                ('input_uri', models.CharField(max_length=1024)),
                ('input_sha256', models.CharField(db_index=True, max_length=64)),
                ('file_size_bytes', models.PositiveBigIntegerField()),
                ('content_type', models.CharField(default='application/gzip', max_length=100)),
                ('performed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_ct_cases', to=settings.AUTH_USER_MODEL)),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ct_cases', to='appointments.encounter')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InferenceJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 일시')),
                ('status', models.CharField(choices=[('QUEUED', '대기'), ('PREPARING', '준비 중'), ('RUNNING', '추론 중'), ('SUCCEEDED', '완료'), ('FAILED', '실패'), ('CANCELLED', '취소'), ('TIMED_OUT', '시간 초과')], default='QUEUED', max_length=16)),
                ('progress', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('error_code', models.CharField(blank=True, max_length=100)),
                ('error_message', models.TextField(blank=True)),
                ('error_retryable', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inference_jobs', to='ct_analysis.ctcase')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_inference_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InferenceResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 일시')),
                ('model_id', models.CharField(max_length=100)),
                ('model_version', models.CharField(max_length=50)),
                ('checkpoint', models.CharField(blank=True, max_length=255)),
                ('threshold', models.DecimalField(blank=True, decimal_places=5, max_digits=6, null=True)),
                ('mask_uri', models.CharField(max_length=1024)),
                ('preview_uri', models.CharField(blank=True, max_length=1024)),
                ('probability_uri', models.CharField(blank=True, max_length=1024)),
                ('entropy_uri', models.CharField(blank=True, max_length=1024)),
                ('uncertainty_uri', models.CharField(blank=True, max_length=1024)),
                ('xai_uri', models.CharField(blank=True, max_length=1024)),
                ('lesion_voxels', models.PositiveBigIntegerField(default=0)),
                ('lesion_volume_ml', models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True)),
                ('lesion_slice_count', models.PositiveIntegerField(default=0)),
                ('lesion_slice_start', models.PositiveIntegerField(blank=True, null=True)),
                ('lesion_slice_end', models.PositiveIntegerField(blank=True, null=True)),
                ('max_lesion_slice', models.PositiveIntegerField(blank=True, null=True)),
                ('shape', models.JSONField(blank=True, default=list)),
                ('spacing', models.JSONField(blank=True, default=list)),
                ('preprocessing_seconds', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('inference_seconds', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('postprocessing_seconds', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('total_seconds', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('gpu_memory_peak_mb', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('raw_result', models.JSONField(blank=True, default=dict)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inference_results', to='ct_analysis.ctcase')),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='result', to='ct_analysis.inferencejob')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='ctcase',
            index=models.Index(fields=['status', 'created_at'], name='ctcase_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='ctcase',
            index=models.Index(fields=['encounter', 'performed_at'], name='ctcase_encounter_date_idx'),
        ),
        migrations.AddIndex(
            model_name='inferencejob',
            index=models.Index(fields=['status', 'created_at'], name='inferjob_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='inferencejob',
            index=models.Index(fields=['case', 'status'], name='inferjob_case_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='inferencejob',
            constraint=models.CheckConstraint(condition=models.Q(('progress__gte', 0), ('progress__lte', 100)), name='inferjob_progress_0_100'),
        ),
        migrations.AddIndex(
            model_name='inferenceresult',
            index=models.Index(fields=['case', 'created_at'], name='inferresult_case_created_idx'),
        ),
        migrations.AddIndex(
            model_name='inferenceresult',
            index=models.Index(fields=['model_id', 'model_version'], name='inferresult_model_idx'),
        ),
        migrations.AddConstraint(
            model_name='inferenceresult',
            constraint=models.CheckConstraint(condition=models.Q(('threshold__isnull', True), models.Q(('threshold__gte', 0), ('threshold__lte', 1)), _connector='OR'), name='inferresult_threshold_0_1'),
        ),
    ]
