# Generated by Django 5.2.16 on 2026-07-31 18:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0002_patient_delete_patientprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CTCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('study_type', models.CharField(choices=[('BRAIN_CT', 'Brain CT')], default='BRAIN_CT', max_length=16)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('UPLOADING', 'Uploading'), ('UPLOADED', 'Uploaded'), ('INFERENCE_QUEUED', 'Inference queued'), ('INFERENCE_RUNNING', 'Inference running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='CREATED', max_length=24)),
                ('input_uri', models.CharField(blank=True, max_length=1000)),
                ('input_sha256', models.CharField(blank=True, max_length=64)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_ct_cases', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ct_cases', to='patients.patient')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InferenceJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='QUEUED', max_length=16)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('error_code', models.CharField(blank=True, max_length=100)),
                ('error_message', models.TextField(blank=True)),
                ('error_retryable', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='ct_analysis.ctcase')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inference_jobs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InferenceResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model_id', models.CharField(max_length=100)),
                ('model_version', models.CharField(max_length=100)),
                ('checkpoint', models.CharField(blank=True, max_length=255)),
                ('threshold', models.FloatField(blank=True, null=True)),
                ('mask_uri', models.CharField(blank=True, max_length=1000)),
                ('preview_uri', models.CharField(blank=True, max_length=1000)),
                ('lesion_voxels', models.BigIntegerField(default=0)),
                ('lesion_volume_ml', models.FloatField(default=0)),
                ('lesion_slice_count', models.PositiveIntegerField(default=0)),
                ('lesion_slice_start', models.IntegerField(blank=True, null=True)),
                ('lesion_slice_end', models.IntegerField(blank=True, null=True)),
                ('max_lesion_slice', models.IntegerField(blank=True, null=True)),
                ('shape', models.JSONField(default=list)),
                ('spacing', models.JSONField(default=list)),
                ('preprocessing_seconds', models.FloatField(default=0)),
                ('inference_seconds', models.FloatField(default=0)),
                ('postprocessing_seconds', models.FloatField(default=0)),
                ('total_seconds', models.FloatField(default=0)),
                ('raw_result', models.JSONField(default=dict)),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='ct_analysis.ctcase')),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='ct_analysis.inferencejob')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='inferencejob',
            constraint=models.CheckConstraint(condition=models.Q(('progress__gte', 0), ('progress__lte', 100)), name='inference_job_progress_range'),
        ),
    ]
