# Generated by Django 5.2.16 on 2026-08-04 02:56

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ct_analysis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModelVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 일시')),
                ('model_key', models.CharField(max_length=100)),
                ('display_name', models.CharField(max_length=200)),
                ('version', models.CharField(max_length=64)),
                ('framework', models.CharField(blank=True, max_length=64)),
                ('checkpoint_uri', models.CharField(blank=True, max_length=1024)),
                ('checkpoint_sha256', models.CharField(blank=True, max_length=64)),
                ('input_schema_version', models.CharField(blank=True, max_length=32)),
                ('output_schema_version', models.CharField(blank=True, max_length=32)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deployed_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['model_key', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InferenceArtifact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 일시')),
                ('artifact_type', models.CharField(choices=[('SEGMENTATION_MASK', '분할 마스크'), ('PROBABILITY_MAP', '확률맵'), ('ENTROPY_MAP', '엔트로피맵'), ('UNCERTAINTY_MAP', '불확실성맵'), ('XAI_MAP', 'XAI 맵'), ('PREVIEW_IMAGE', '미리보기'), ('REPORT_JSON', '결과 JSON'), ('OTHER', '기타')], db_index=True, max_length=24)),
                ('label', models.CharField(blank=True, max_length=100)),
                ('coordinate_space', models.CharField(blank=True, max_length=64)),
                ('is_primary', models.BooleanField(db_index=True, default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['artifact_type', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='InferenceFinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 일시')),
                ('finding_number', models.PositiveIntegerField()),
                ('finding_type', models.CharField(max_length=100)),
                ('label', models.CharField(blank=True, max_length=100)),
                ('confidence', models.DecimalField(blank=True, decimal_places=6, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('lesion_voxels', models.PositiveBigIntegerField(default=0)),
                ('lesion_volume_ml', models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True)),
                ('slice_start', models.PositiveIntegerField(blank=True, null=True)),
                ('slice_end', models.PositiveIntegerField(blank=True, null=True)),
                ('max_slice', models.PositiveIntegerField(blank=True, null=True)),
                ('centroid', models.JSONField(blank=True, default=list)),
                ('bounding_box', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['finding_number'],
            },
        ),
        migrations.CreateModel(
            name='InferenceReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 일시')),
                ('sequence', models.PositiveIntegerField(default=1)),
                ('decision', models.CharField(choices=[('NEEDS_REVIEW', '검토 필요'), ('ACCEPTED', '승인'), ('REJECTED', '반려'), ('MODIFIED', '수정')], db_index=True, default='NEEDS_REVIEW', max_length=16)),
                ('comment', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['sequence', 'created_at'],
            },
        ),
    ]
