# Generated by Django 5.2.16 on 2026-08-04 02:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_appointmentstatushistory_appointment_cancelled_by_and_more'),
        ('assets', '0001_initial'),
        ('clinicians', '0002_clinicianavailability_cliniciantimeoff'),
        ('ct_analysis', '0002_aimodelversion_inferenceartifact_inferencefinding_and_more'),
        ('imaging', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ctcase',
            name='imaging_study',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ct_cases', to='imaging.imagingstudy'),
        ),
        migrations.AddField(
            model_name='inferencejob',
            name='idempotency_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ctcase',
            name='encounter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ct_cases', to='appointments.encounter'),
        ),
        migrations.AddIndex(
            model_name='ctcase',
            index=models.Index(fields=['imaging_study', 'status'], name='ctcase_study_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='ctcase',
            constraint=models.CheckConstraint(condition=models.Q(('encounter__isnull', False), ('imaging_study__isnull', False), _connector='OR'), name='ctcase_clinical_source_req'),
        ),
        migrations.AddConstraint(
            model_name='aimodelversion',
            constraint=models.UniqueConstraint(fields=('model_key', 'version'), name='aimodel_key_version_uniq'),
        ),
        migrations.AddField(
            model_name='inferencejob',
            name='model_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inference_jobs', to='ct_analysis.aimodelversion'),
        ),
        migrations.AddField(
            model_name='inferenceresult',
            name='model_version_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inference_results', to='ct_analysis.aimodelversion'),
        ),
        migrations.AddConstraint(
            model_name='inferencejob',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key__isnull', False), models.Q(('idempotency_key', ''), _negated=True)), fields=('case', 'idempotency_key'), name='inferjob_case_idem_uniq'),
        ),
        migrations.AddField(
            model_name='inferenceartifact',
            name='result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='ct_analysis.inferenceresult'),
        ),
        migrations.AddField(
            model_name='inferenceartifact',
            name='stored_object',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='inference_artifact', to='assets.storedobject'),
        ),
        migrations.AddField(
            model_name='inferencefinding',
            name='result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='ct_analysis.inferenceresult'),
        ),
        migrations.AddField(
            model_name='inferencereview',
            name='corrected_artifact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='review_corrections', to='ct_analysis.inferenceartifact'),
        ),
        migrations.AddField(
            model_name='inferencereview',
            name='result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='ct_analysis.inferenceresult'),
        ),
        migrations.AddField(
            model_name='inferencereview',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inference_reviews', to='clinicians.clinician'),
        ),
        migrations.AddConstraint(
            model_name='inferenceartifact',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('result', 'artifact_type', 'label'), name='inferartifact_primary_uniq'),
        ),
        migrations.AddConstraint(
            model_name='inferencefinding',
            constraint=models.UniqueConstraint(fields=('result', 'finding_number'), name='inferfinding_number_uniq'),
        ),
        migrations.AddConstraint(
            model_name='inferencefinding',
            constraint=models.CheckConstraint(condition=models.Q(('confidence__isnull', True), models.Q(('confidence__gte', 0), ('confidence__lte', 1)), _connector='OR'), name='inferfinding_confidence_valid'),
        ),
        migrations.AddConstraint(
            model_name='inferencefinding',
            constraint=models.CheckConstraint(condition=models.Q(('slice_start__isnull', True), ('slice_end__isnull', True), ('slice_end__gte', models.F('slice_start')), _connector='OR'), name='inferfinding_slice_valid'),
        ),
        migrations.AddConstraint(
            model_name='inferencereview',
            constraint=models.UniqueConstraint(fields=('result', 'sequence'), name='inferreview_result_seq_uniq'),
        ),
    ]
