# Generated by Django 5.2.16 on 2026-08-04 03:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
        ('ct_analysis', '0003_ctcase_imaging_study_inferencejob_idempotency_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodelversion',
            name='checkpoint_object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ai_model_checkpoints', to='assets.storedobject'),
        ),
    ]
