# Generated by Django 5.2.16 on 2026-08-01 20:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinicians', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 일시')),
                ('scheduled_at', models.DateTimeField(db_index=True)),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('SCHEDULED', '예약'), ('CONFIRMED', '확정'), ('CHECKED_IN', '접수'), ('COMPLETED', '완료'), ('CANCELLED', '취소'), ('NO_SHOW', '미방문')], default='SCHEDULED', max_length=16)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('clinician', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='clinicians.clinician')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='clinicians.department')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='patients.patient')),
            ],
            options={
                'ordering': ['scheduled_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Encounter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 일시')),
                ('encounter_number', models.CharField(max_length=40, unique=True)),
                ('encounter_type', models.CharField(choices=[('OUTPATIENT', '외래'), ('EMERGENCY', '응급'), ('INPATIENT', '입원'), ('TELEMEDICINE', '비대면')], max_length=16)),
                ('status', models.CharField(choices=[('REGISTERED', '등록'), ('ARRIVED', '도착'), ('IN_PROGRESS', '진료 중'), ('COMPLETED', '완료'), ('CANCELLED', '취소')], default='REGISTERED', max_length=16)),
                ('arrived_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('appointment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='encounter', to='appointments.appointment')),
                ('attending_clinician', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attended_encounters', to='clinicians.clinician')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='encounters', to='clinicians.department')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='encounters', to='patients.patient')),
                ('provisional_identity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='encounters', to='patients.provisionalidentity')),
                ('registered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registered_encounters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['status', 'scheduled_at'], name='appointment_status_date_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['patient', 'scheduled_at'], name='appointment_patient_date_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['clinician', 'scheduled_at'], name='appointment_clinician_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'CANCELLED'), _negated=True), ('cancelled_at__isnull', False), _connector='OR'), name='appointment_cancelled_at_required'),
        ),
        migrations.AddIndex(
            model_name='encounter',
            index=models.Index(fields=['status', 'created_at'], name='encounter_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='encounter',
            index=models.Index(fields=['patient', 'created_at'], name='encounter_patient_created_idx'),
        ),
        migrations.AddIndex(
            model_name='encounter',
            index=models.Index(fields=['provisional_identity', 'created_at'], name='encounter_provisional_idx'),
        ),
        migrations.AddIndex(
            model_name='encounter',
            index=models.Index(fields=['attending_clinician', 'created_at'], name='encounter_clinician_idx'),
        ),
        migrations.AddConstraint(
            model_name='encounter',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('patient__isnull', False), ('provisional_identity__isnull', True)), models.Q(('patient__isnull', True), ('provisional_identity__isnull', False)), _connector='OR'), name='encounter_exactly_one_identity'),
        ),
        migrations.AddConstraint(
            model_name='encounter',
            constraint=models.CheckConstraint(condition=models.Q(('arrived_at__isnull', True), ('started_at__isnull', True), ('started_at__gte', models.F('arrived_at')), _connector='OR'), name='encounter_start_after_arrival'),
        ),
        migrations.AddConstraint(
            model_name='encounter',
            constraint=models.CheckConstraint(condition=models.Q(('started_at__isnull', True), ('completed_at__isnull', True), ('completed_at__gte', models.F('started_at')), _connector='OR'), name='encounter_complete_after_start'),
        ),
        migrations.AddConstraint(
            model_name='encounter',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'COMPLETED'), _negated=True), ('completed_at__isnull', False), _connector='OR'), name='encounter_completed_at_required'),
        ),
    ]
