# Generated by Django 5.2.16 on 2026-08-02 07:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
        ('clinicians', '0001_initial'),
        ('hospitals', '0003_hospital_external_place_id_and_more'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='hospitals.hospital', verbose_name='진료 병원'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='location',
            field=models.CharField(blank=True, help_text='예: 본관 2층 내과 진료실', max_length=255, verbose_name='진료 위치'),
        ),
        migrations.AddField(
            model_name='encounter',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='encounters', to='hospitals.hospital', verbose_name='진료 병원'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['hospital', 'scheduled_at'], name='appointment_hospital_date_idx'),
        ),
        migrations.AddIndex(
            model_name='encounter',
            index=models.Index(fields=['hospital', 'created_at'], name='encounter_hospital_created_idx'),
        ),
    ]
