# Generated by Django 5.2.16 on 2026-08-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "appointments",
            "0002_appointment_hospital_appointment_location_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="duration_minutes",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (15, "15분"),
                    (30, "30분"),
                    (60, "60분"),
                ],
                default=30,
                verbose_name="예약 소요시간(분)",
            ),
        ),
    ]
