# Generated by Django 5.2.16 on 2026-08-03 07:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_appointment_duration_minutes'),
        ('clinicians', '0002_clinicianavailability_cliniciantimeoff'),
        ('hospitals', '0003_hospital_external_place_id_and_more'),
        ('patients', '0004_provisional_identity_chart_trigger'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentStatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 일시')),
                ('previous_status', models.CharField(blank=True, choices=[('SCHEDULED', '예약'), ('CONFIRMED', '확정'), ('CHECKED_IN', '접수'), ('COMPLETED', '완료'), ('CANCELLED', '취소'), ('NO_SHOW', '미방문')], max_length=16, verbose_name='이전 상태')),
                ('new_status', models.CharField(choices=[('SCHEDULED', '예약'), ('CONFIRMED', '확정'), ('CHECKED_IN', '접수'), ('COMPLETED', '완료'), ('CANCELLED', '취소'), ('NO_SHOW', '미방문')], max_length=16, verbose_name='변경 상태')),
                ('reason', models.TextField(blank=True, verbose_name='변경 사유')),
            ],
            options={
                'verbose_name': '예약 상태 이력',
                'verbose_name_plural': '예약 상태 이력',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cancelled_appointments', to=settings.AUTH_USER_MODEL, verbose_name='예약 취소자'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_appointments', to=settings.AUTH_USER_MODEL, verbose_name='예약 생성자'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.CheckConstraint(condition=models.Q(('status', 'CANCELLED'), ('cancelled_by__isnull', True), _connector='OR'), name='appointment_cancelled_by_valid'),
        ),
        migrations.AddField(
            model_name='appointmentstatushistory',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='appointments.appointment', verbose_name='예약'),
        ),
        migrations.AddField(
            model_name='appointmentstatushistory',
            name='changed_by',
            field=models.ForeignKey(blank=True, help_text='자동 처리나 기존 데이터 이관이면 비워둘 수 있습니다.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='appointment_status_changes', to=settings.AUTH_USER_MODEL, verbose_name='변경자'),
        ),
        migrations.AddIndex(
            model_name='appointmentstatushistory',
            index=models.Index(fields=['appointment', 'created_at'], name='appt_history_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='appointmentstatushistory',
            constraint=models.CheckConstraint(condition=models.Q(('previous_status', ''), models.Q(('previous_status', models.F('new_status')), _negated=True), _connector='OR'), name='appt_history_status_changed'),
        ),
        migrations.AddConstraint(
            model_name='appointmentstatushistory',
            constraint=models.UniqueConstraint(condition=models.Q(('previous_status', '')), fields=('appointment',), name='appt_history_one_initial'),
        ),
    ]
