# Generated by Django 5.2.16 on 2026-08-01 21:33

import apps.medications.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prescriptions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicationSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 일시')),
                ('dose_time', models.TimeField(verbose_name='복용 예정 시간')),
                ('days_of_week', models.JSONField(blank=True, default=list, help_text='ISO 요일 기준 1=월요일, 7=일요일입니다. 빈 배열은 매일 복용을 의미합니다.', validators=[apps.medications.models.validate_days_of_week], verbose_name='복용 요일')),
                ('start_date', models.DateField(verbose_name='복약 시작일')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='복약 종료일')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='활성 여부')),
                ('prescription_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medication_schedules', to='prescriptions.prescriptionitem', verbose_name='처방 약품')),
            ],
            options={
                'verbose_name': '복약 일정',
                'verbose_name_plural': '복약 일정',
                'ordering': ['start_date', 'dose_time', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicationRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 일시')),
                ('scheduled_at', models.DateTimeField(db_index=True, verbose_name='복용 예정 일시')),
                ('taken_at', models.DateTimeField(blank=True, null=True, verbose_name='실제 복용 일시')),
                ('status', models.CharField(choices=[('TAKEN', '복용 완료'), ('MISSED', '미복용'), ('SKIPPED', '복용 건너뜀')], db_index=True, max_length=16, verbose_name='복약 상태')),
                ('note', models.TextField(blank=True, verbose_name='복약 메모')),
                ('prescription_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medication_records', to='prescriptions.prescriptionitem', verbose_name='처방 약품')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medication_records', to='medications.medicationschedule', verbose_name='복약 일정')),
            ],
            options={
                'verbose_name': '복약 기록',
                'verbose_name_plural': '복약 기록',
                'ordering': ['-scheduled_at', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='medicationschedule',
            index=models.Index(fields=['prescription_item', 'is_active'], name='medsched_item_active_idx'),
        ),
        migrations.AddIndex(
            model_name='medicationschedule',
            index=models.Index(fields=['is_active', 'start_date', 'end_date'], name='medsched_active_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='medicationschedule',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='medschedule_end_after_start'),
        ),
        migrations.AddIndex(
            model_name='medicationrecord',
            index=models.Index(fields=['schedule', 'scheduled_at'], name='medrecord_schedule_time_idx'),
        ),
        migrations.AddIndex(
            model_name='medicationrecord',
            index=models.Index(fields=['prescription_item', 'scheduled_at'], name='medrecord_item_time_idx'),
        ),
        migrations.AddIndex(
            model_name='medicationrecord',
            index=models.Index(fields=['status', 'scheduled_at'], name='medrecord_status_time_idx'),
        ),
        migrations.AddConstraint(
            model_name='medicationrecord',
            constraint=models.UniqueConstraint(fields=('schedule', 'scheduled_at'), name='medrecord_schedule_at_uniq'),
        ),
        migrations.AddConstraint(
            model_name='medicationrecord',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'TAKEN'), ('taken_at__isnull', False)), models.Q(models.Q(('status', 'TAKEN'), _negated=True), ('taken_at__isnull', True)), _connector='OR'), name='medrecord_taken_at_valid'),
        ),
    ]
