# Generated by Django 5.2.16 on 2026-07-31 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medications', '0001_initial'),
        ('prescriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicationrecord',
            name='prescription_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medication_records', to='prescriptions.prescriptionitem'),
        ),
        migrations.AddField(
            model_name='medicationschedule',
            name='prescription_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='prescriptions.prescriptionitem'),
        ),
        migrations.AddField(
            model_name='medicationrecord',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='medications.medicationschedule'),
        ),
        migrations.AddConstraint(
            model_name='medicationrecord',
            constraint=models.UniqueConstraint(condition=models.Q(('schedule__isnull', False)), fields=('patient', 'schedule'), name='unique_medication_record_per_patient_schedule'),
        ),
    ]
