# Generated by Django 5.2.16 on 2026-08-04 02:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0004_appointmentstatushistory_appointment_cancelled_by_and_more'),
        ('patients', '0004_provisional_identity_chart_trigger'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 일시')),
                ('action', models.CharField(choices=[('CREATED', '생성'), ('VIEWED', '열람'), ('UPDATED', '수정'), ('DELETED', '삭제'), ('DOWNLOADED', '다운로드'), ('EXPORTED', '내보내기'), ('RELEASED', '환자 공개'), ('ANALYSIS_REQUESTED', 'AI 분석 요청'), ('TOOL_EXECUTED', '챗봇 도구 실행'), ('AUTHENTICATED', '인증'), ('PERMISSION_DENIED', '접근 거부')], db_index=True, max_length=32)),
                ('resource_type', models.CharField(db_index=True, max_length=100)),
                ('resource_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('request_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('outcome', models.CharField(db_index=True, default='SUCCESS', max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
                ('encounter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to='appointments.encounter')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to='patients.patient')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['actor', 'created_at'], name='audit_actor_date_idx'), models.Index(fields=['patient', 'created_at'], name='audit_patient_date_idx'), models.Index(fields=['resource_type', 'resource_id'], name='audit_resource_idx')],
            },
        ),
    ]
