# Generated by Django 5.2.16 on 2026-08-01 20:05

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospitals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='진료과 UUID')),
                ('code', models.CharField(db_index=True, max_length=30, unique=True, verbose_name='진료과 코드')),
                ('name', models.CharField(max_length=100, verbose_name='진료과명')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='사용 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 일시')),
            ],
            options={
                'verbose_name': '진료과',
                'verbose_name_plural': '진료과',
                'db_table': 'departments',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Clinician',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='의료진 UUID')),
                ('name', models.CharField(max_length=100, verbose_name='의료진 이름')),
                ('license_number', models.CharField(db_index=True, max_length=6, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_license_number', message='면허번호는 숫자 6자리여야 합니다.', regex='^\\d{6}$')], verbose_name='면허번호')),
                ('approval_status', models.CharField(choices=[('PENDING', '승인 대기'), ('APPROVED', '승인 완료'), ('REJECTED', '승인 거절'), ('SUSPENDED', '이용 정지')], db_index=True, default='PENDING', max_length=20, verbose_name='승인 상태')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='승인 일시')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='가입 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 일시')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_clinicians', to=settings.AUTH_USER_MODEL, verbose_name='승인 관리자')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clinicians', to='hospitals.hospital', verbose_name='소속 병원')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clinician', to=settings.AUTH_USER_MODEL, verbose_name='사용자 계정')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clinicians', to='clinicians.department', verbose_name='진료과')),
            ],
            options={
                'verbose_name': '의료진',
                'verbose_name_plural': '의료진',
                'db_table': 'clinicians',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['hospital', 'department'], name='clinician_hospital_dept_idx'), models.Index(fields=['approval_status'], name='clinician_approval_idx')],
            },
        ),
    ]
