# Generated by Django 5.2.16 on 2026-08-03 07:35

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicians', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicianAvailability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 일시')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, '월요일'), (1, '화요일'), (2, '수요일'), (3, '목요일'), (4, '금요일'), (5, '토요일'), (6, '일요일')], verbose_name='요일')),
                ('start_time', models.TimeField(verbose_name='진료 시작 시간')),
                ('end_time', models.TimeField(verbose_name='진료 종료 시간')),
                ('effective_from', models.DateField(default=django.utils.timezone.localdate, verbose_name='적용 시작일')),
                ('effective_to', models.DateField(blank=True, null=True, verbose_name='적용 종료일')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='활성 여부')),
                ('clinician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='clinicians.clinician', verbose_name='의료진')),
            ],
            options={
                'verbose_name': '의료진 진료 가능 시간',
                'verbose_name_plural': '의료진 진료 가능 시간',
                'ordering': ['clinician', 'weekday', 'start_time'],
                'indexes': [models.Index(fields=['clinician', 'weekday', 'is_active'], name='clin_avail_day_idx'), models.Index(fields=['effective_from', 'effective_to'], name='clin_avail_period_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('weekday__range', (0, 6))), name='clin_avail_weekday_valid'), models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='clin_avail_end_after_start'), models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_to__gte', models.F('effective_from')), _connector='OR'), name='clin_avail_period_valid'), models.UniqueConstraint(fields=('clinician', 'weekday', 'start_time', 'end_time', 'effective_from'), name='clin_avail_slot_unique')],
            },
        ),
        migrations.CreateModel(
            name='ClinicianTimeOff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 일시')),
                ('start_at', models.DateTimeField(db_index=True, verbose_name='시작 일시')),
                ('end_at', models.DateTimeField(db_index=True, verbose_name='종료 일시')),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='사유')),
                ('clinician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_offs', to='clinicians.clinician', verbose_name='의료진')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_clinician_time_offs', to=settings.AUTH_USER_MODEL, verbose_name='등록자')),
            ],
            options={
                'verbose_name': '의료진 진료 불가 시간',
                'verbose_name_plural': '의료진 진료 불가 시간',
                'ordering': ['start_at'],
                'indexes': [models.Index(fields=['clinician', 'start_at', 'end_at'], name='clin_time_off_period_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_at__gt', models.F('start_at'))), name='clin_time_off_end_after_start'), models.UniqueConstraint(fields=('clinician', 'start_at', 'end_at'), name='clin_time_off_period_unique')],
            },
        ),
    ]
