# Generated by Django 5.2.16 on 2026-08-04 02:56

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0004_appointmentstatushistory_appointment_cancelled_by_and_more'),
        ('clinical_records', '0001_initial'),
        ('clinicians', '0002_clinicianavailability_cliniciantimeoff'),
        ('hospitals', '0003_hospital_external_place_id_and_more'),
        ('prescriptions', '0001_initial'),
        ('test_results', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentationDeficiency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 일시')),
                ('detection_source', models.CharField(choices=[('AUTOMATIC', '자동 판정'), ('MANUAL', '수동 등록')], default='AUTOMATIC', max_length=16)),
                ('document_type', models.CharField(choices=[('CLINICAL_RECORD', '진료기록'), ('DIAGNOSIS', '진단'), ('PRESCRIPTION', '처방'), ('TEST_RESULT', '검사결과'), ('CONSULTATION', '협진기록'), ('DISCHARGE_SUMMARY', '퇴원요약'), ('SIGNATURE', '전자서명'), ('OTHER', '기타')], db_index=True, max_length=24)),
                ('title', models.CharField(max_length=200)),
                ('details', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('OPEN', '미비'), ('IN_PROGRESS', '보완 중'), ('SUBMITTED', '검토 요청'), ('RESOLVED', '완료'), ('REJECTED', '보완 반려'), ('WAIVED', '면제')], db_index=True, default='OPEN', max_length=16)),
                ('detected_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('due_at', models.DateTimeField(db_index=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.TextField(blank=True)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_documentation_deficiencies', to='clinicians.clinician')),
                ('clinical_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentation_deficiencies', to='clinical_records.clinicalrecord')),
                ('detected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='detected_documentation_deficiencies', to=settings.AUTH_USER_MODEL)),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentation_deficiencies', to='appointments.encounter')),
                ('prescription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentation_deficiencies', to='prescriptions.prescription')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resolved_documentation_deficiencies', to=settings.AUTH_USER_MODEL)),
                ('test_result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentation_deficiencies', to='test_results.testresult')),
            ],
            options={
                'ordering': ['due_at', '-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentationReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 일시')),
                ('decision', models.CharField(choices=[('APPROVED', '승인'), ('REJECTED', '반려'), ('WAIVED', '면제')], max_length=16)),
                ('comment', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('deficiency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='documentation.documentationdeficiency')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentation_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-reviewed_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentationRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 일시')),
                ('rule_code', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=200)),
                ('document_type', models.CharField(choices=[('CLINICAL_RECORD', '진료기록'), ('DIAGNOSIS', '진단'), ('PRESCRIPTION', '처방'), ('TEST_RESULT', '검사결과'), ('CONSULTATION', '협진기록'), ('DISCHARGE_SUMMARY', '퇴원요약'), ('SIGNATURE', '전자서명'), ('OTHER', '기타')], max_length=24)),
                ('encounter_type', models.CharField(blank=True, max_length=16)),
                ('required_fields', models.JSONField(blank=True, default=list)),
                ('completion_due_minutes', models.PositiveIntegerField(default=1440)),
                ('severity', models.CharField(default='WARNING', max_length=16)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('description', models.TextField(blank=True)),
                ('hospital', models.ForeignKey(blank=True, help_text='비어 있으면 모든 병원에 적용되는 기본 규칙입니다.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentation_rules', to='hospitals.hospital')),
            ],
            options={
                'ordering': ['document_type', 'name'],
            },
        ),
        migrations.AddField(
            model_name='documentationdeficiency',
            name='rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deficiencies', to='documentation.documentationrule'),
        ),
        migrations.CreateModel(
            name='DocumentationStatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 일시')),
                ('previous_status', models.CharField(blank=True, max_length=16)),
                ('new_status', models.CharField(choices=[('OPEN', '미비'), ('IN_PROGRESS', '보완 중'), ('SUBMITTED', '검토 요청'), ('RESOLVED', '완료'), ('REJECTED', '보완 반려'), ('WAIVED', '면제')], max_length=16)),
                ('reason', models.TextField(blank=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentation_status_changes', to=settings.AUTH_USER_MODEL)),
                ('deficiency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status_history', to='documentation.documentationdeficiency')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentationDeficiencyItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 일시')),
                ('item_code', models.CharField(max_length=64)),
                ('field_name', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('sequence', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('MISSING', '누락'), ('RESOLVED', '보완'), ('WAIVED', '면제')], db_index=True, default='MISSING', max_length=16)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.TextField(blank=True)),
                ('deficiency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='documentation.documentationdeficiency')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resolved_documentation_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sequence', 'created_at'],
                'constraints': [models.UniqueConstraint(fields=('deficiency', 'item_code'), name='docdefitem_code_uniq'), models.CheckConstraint(condition=models.Q(models.Q(('resolved_at__isnull', True), ('resolved_by__isnull', True), ('status', 'MISSING')), models.Q(('resolved_at__isnull', False), ('resolved_by__isnull', False), ('status__in', ['RESOLVED', 'WAIVED'])), _connector='OR'), name='docdefitem_resolution_valid')],
            },
        ),
        migrations.AddConstraint(
            model_name='documentationrule',
            constraint=models.UniqueConstraint(condition=models.Q(('hospital__isnull', False)), fields=('hospital', 'rule_code', 'encounter_type'), name='docrule_hospital_code_uniq'),
        ),
        migrations.AddConstraint(
            model_name='documentationrule',
            constraint=models.UniqueConstraint(condition=models.Q(('hospital__isnull', True)), fields=('rule_code', 'encounter_type'), name='docrule_default_code_uniq'),
        ),
        migrations.AddIndex(
            model_name='documentationdeficiency',
            index=models.Index(fields=['assigned_to', 'status', 'due_at'], name='docdef_assignee_status_idx'),
        ),
        migrations.AddIndex(
            model_name='documentationdeficiency',
            index=models.Index(fields=['encounter', 'status'], name='docdef_encounter_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='documentationdeficiency',
            constraint=models.CheckConstraint(condition=models.Q(('due_at__gte', models.F('detected_at'))), name='docdef_due_after_detected'),
        ),
        migrations.AddConstraint(
            model_name='documentationdeficiency',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('resolved_at__isnull', False), ('status__in', ['RESOLVED', 'WAIVED'])), models.Q(('status__in', ['RESOLVED', 'WAIVED']), _negated=True), _connector='OR'), name='docdef_resolved_at_req'),
        ),
        migrations.AddIndex(
            model_name='documentationstatushistory',
            index=models.Index(fields=['deficiency', 'created_at'], name='docdefhist_def_date_idx'),
        ),
    ]
