# Generated by Django 5.2.16 on 2026-08-04 03:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_appointmentstatushistory_appointment_cancelled_by_and_more'),
        ('clinical_records', '0001_initial'),
        ('clinicians', '0002_clinicianavailability_cliniciantimeoff'),
        ('documentation', '0001_initial'),
        ('prescriptions', '0001_initial'),
        ('test_results', '0002_testresultstatushistory_testresult_finalized_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='documentationdeficiency',
            name='docdef_resolved_at_req',
        ),
        migrations.AddConstraint(
            model_name='documentationdeficiency',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('resolved_at__isnull', False), ('resolved_by__isnull', False), ('status__in', ['RESOLVED', 'WAIVED'])), models.Q(('status__in', ['RESOLVED', 'WAIVED']), _negated=True), _connector='OR'), name='docdef_resolved_at_req'),
        ),
        migrations.AddConstraint(
            model_name='documentationdeficiency',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('clinical_record__isnull', False), ('prescription__isnull', False), _negated=True), models.Q(('clinical_record__isnull', False), ('test_result__isnull', False), _negated=True), models.Q(('prescription__isnull', False), ('test_result__isnull', False), _negated=True)), name='docdef_at_most_one_source'),
        ),
    ]
