# Generated by Django 5.2.16 on 2026-08-01 20:48

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        ('clinicians', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 일시')),
                ('recorded_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='기록 일시')),
                ('chief_complaint', models.TextField(blank=True, verbose_name='주호소')),
                ('subjective', models.TextField(blank=True, verbose_name='주관적 정보')),
                ('objective', models.TextField(blank=True, verbose_name='객관적 정보')),
                ('assessment', models.TextField(blank=True, verbose_name='평가')),
                ('plan', models.TextField(blank=True, verbose_name='계획')),
                ('patient_visible_summary', models.TextField(blank=True, verbose_name='환자 공개 요약')),
                ('clinician', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clinical_records', to='clinicians.clinician', verbose_name='작성 의료진')),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clinical_records', to='appointments.encounter', verbose_name='진료 건')),
            ],
            options={
                'verbose_name': '진료기록',
                'verbose_name_plural': '진료기록',
                'ordering': ['-recorded_at', '-created_at'],
                'indexes': [models.Index(fields=['encounter', 'recorded_at'], name='clinicalrec_encounter_idx'), models.Index(fields=['clinician', 'recorded_at'], name='clinicalrec_clinician_idx')],
            },
        ),
    ]
