# Generated by Django 5.2.16 on 2026-08-01 21:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        ('clinicians', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 일시')),
                ('question', models.TextField(verbose_name='협진 요청 내용')),
                ('response', models.TextField(blank=True, verbose_name='협진 답변')),
                ('status', models.CharField(choices=[('REQUESTED', '협진 요청'), ('IN_PROGRESS', '협진 진행 중'), ('COMPLETED', '협진 완료'), ('CANCELLED', '협진 취소')], db_index=True, default='REQUESTED', max_length=16, verbose_name='협진 상태')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='협진 완료 일시')),
                ('consultant_clinician', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_consultations', to='clinicians.clinician', verbose_name='협진 담당 의료진')),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consultations', to='appointments.encounter', verbose_name='진료 건')),
                ('requester_clinician', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_consultations', to='clinicians.clinician', verbose_name='협진 요청 의료진')),
            ],
            options={
                'verbose_name': '협진',
                'verbose_name_plural': '협진',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['encounter', 'status'], name='consult_encounter_status_idx'), models.Index(fields=['requester_clinician', 'created_at'], name='consult_requester_date_idx'), models.Index(fields=['consultant_clinician', 'status'], name='consult_consultant_status_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('requester_clinician', models.F('consultant_clinician')), _negated=True), name='consultation_different_clinicians'), models.CheckConstraint(condition=models.Q(models.Q(('completed_at__isnull', False), ('status', 'COMPLETED')), models.Q(models.Q(('status', 'COMPLETED'), _negated=True), ('completed_at__isnull', True)), _connector='OR'), name='consultation_completed_at_valid'), models.CheckConstraint(condition=models.Q(models.Q(('status', 'COMPLETED'), _negated=True), models.Q(('response', ''), _negated=True), _connector='OR'), name='consultation_response_required')],
            },
        ),
    ]
