# Generated by Django 5.2.16 on 2026-07-31 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinicians', '0002_department_clinician_delete_clinicianprofile'),
        ('consultations', '0001_initial'),
        ('ct_analysis', '0001_initial'),
        ('patients', '0002_patient_delete_patientprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultations', to='ct_analysis.ctcase'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='consultant_clinician',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_consultations', to='clinicians.clinician'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consultations', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='requester_clinician',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_consultations', to='clinicians.clinician'),
        ),
    ]
