# Generated by Django 5.2.16 on 2026-08-04 02:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def populate_consultation_participants(apps, schema_editor):
    Consultation = apps.get_model("consultations", "Consultation")
    Participant = apps.get_model("consultations", "ConsultationParticipant")

    for consultation in Consultation.objects.select_related(
        "requester_clinician",
        "consultant_clinician",
    ).iterator():
        requester_user_id = consultation.requester_clinician.user_id
        Participant.objects.get_or_create(
            consultation_id=consultation.id,
            clinician_id=consultation.requester_clinician_id,
            defaults={
                "role": "REQUESTER",
                "added_by_id": requester_user_id,
            },
        )
        Participant.objects.get_or_create(
            consultation_id=consultation.id,
            clinician_id=consultation.consultant_clinician_id,
            defaults={
                "role": "CONSULTANT",
                "added_by_id": requester_user_id,
            },
        )

        update_fields = []
        if not consultation.subject:
            consultation.subject = consultation.question[:200]
            update_fields.append("subject")
        if consultation.status in {"IN_PROGRESS", "COMPLETED"}:
            consultation.accepted_at = consultation.updated_at
            update_fields.append("accepted_at")
        if consultation.status == "CANCELLED":
            consultation.cancelled_at = consultation.updated_at
            consultation.cancelled_by_id = requester_user_id
            update_fields.extend(["cancelled_at", "cancelled_by_id"])
        if update_fields:
            consultation.save(update_fields=update_fields)


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_appointmentstatushistory_appointment_cancelled_by_and_more'),
        ('assets', '0001_initial'),
        ('clinicians', '0002_clinicianavailability_cliniciantimeoff'),
        ('consultations', '0002_consultationattachment_consultationmessage_and_more'),
        ('ct_analysis', '0002_aimodelversion_inferenceartifact_inferencefinding_and_more'),
        ('imaging', '0001_initial'),
        ('test_results', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationattachment',
            name='imaging_study',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consultation_attachments', to='imaging.imagingstudy'),
        ),
        migrations.AddField(
            model_name='consultationattachment',
            name='inference_result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consultation_attachments', to='ct_analysis.inferenceresult'),
        ),
        migrations.AddField(
            model_name='consultationattachment',
            name='stored_object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consultation_attachments', to='assets.storedobject'),
        ),
        migrations.AddField(
            model_name='consultationattachment',
            name='test_result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consultation_attachments', to='test_results.testresult'),
        ),
        migrations.AddField(
            model_name='consultationmessage',
            name='consultation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='consultations.consultation'),
        ),
        migrations.AddField(
            model_name='consultationmessage',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consultation_messages', to='clinicians.clinician'),
        ),
        migrations.AddField(
            model_name='consultationattachment',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='consultations.consultationmessage'),
        ),
        migrations.AddField(
            model_name='consultationparticipant',
            name='added_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='added_consultation_participants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='consultationparticipant',
            name='clinician',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consultation_participations', to='clinicians.clinician'),
        ),
        migrations.AddField(
            model_name='consultationparticipant',
            name='consultation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='consultations.consultation'),
        ),
        migrations.AddField(
            model_name='consultationstatushistory',
            name='changed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consultation_status_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='consultationstatushistory',
            name='consultation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status_history', to='consultations.consultation'),
        ),
        migrations.AddField(
            model_name='encounteraccessgrant',
            name='consultation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_grants', to='consultations.consultation'),
        ),
        migrations.AddField(
            model_name='encounteraccessgrant',
            name='encounter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consultation_access_grants', to='appointments.encounter'),
        ),
        migrations.AddField(
            model_name='encounteraccessgrant',
            name='granted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='granted_encounter_access', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='encounteraccessgrant',
            name='grantee_clinician',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='encounter_access_grants', to='clinicians.clinician'),
        ),
        migrations.AddField(
            model_name='encounteraccessgrant',
            name='revoked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='revoked_encounter_access', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='consultationmessage',
            constraint=models.UniqueConstraint(fields=('consultation', 'sequence'), name='consult_message_seq_uniq'),
        ),
        migrations.AddConstraint(
            model_name='consultationmessage',
            constraint=models.CheckConstraint(condition=models.Q(('sequence__gte', 1)), name='consult_message_seq_positive'),
        ),
        migrations.AddConstraint(
            model_name='consultationmessage',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('is_system', True), ('sender__isnull', True)), models.Q(('is_system', False), ('sender__isnull', False)), _connector='OR'), name='consult_message_sender_valid'),
        ),
        migrations.AddConstraint(
            model_name='consultationattachment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('imaging_study__isnull', True), ('inference_result__isnull', True), ('stored_object__isnull', False), ('test_result__isnull', True)), models.Q(('imaging_study__isnull', False), ('inference_result__isnull', True), ('stored_object__isnull', True), ('test_result__isnull', True)), models.Q(('imaging_study__isnull', True), ('inference_result__isnull', False), ('stored_object__isnull', True), ('test_result__isnull', True)), models.Q(('imaging_study__isnull', True), ('inference_result__isnull', True), ('stored_object__isnull', True), ('test_result__isnull', False)), _connector='OR'), name='consult_attachment_one_source'),
        ),
        migrations.AddConstraint(
            model_name='consultationparticipant',
            constraint=models.UniqueConstraint(fields=('consultation', 'clinician'), name='consult_participant_uniq'),
        ),
        migrations.AddConstraint(
            model_name='consultationparticipant',
            constraint=models.CheckConstraint(condition=models.Q(('left_at__isnull', True), ('left_at__gte', models.F('joined_at')), _connector='OR'), name='consult_participant_left_valid'),
        ),
        migrations.AddIndex(
            model_name='consultationstatushistory',
            index=models.Index(fields=['consultation', 'created_at'], name='consulthist_consult_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='encounteraccessgrant',
            constraint=models.UniqueConstraint(condition=models.Q(('revoked_at__isnull', True)), fields=('consultation', 'grantee_clinician'), name='consult_active_grant_uniq'),
        ),
        migrations.AddConstraint(
            model_name='encounteraccessgrant',
            constraint=models.CheckConstraint(condition=models.Q(('expires_at__gt', models.F('created_at'))), name='consult_grant_expiry_valid'),
        ),
        migrations.AddConstraint(
            model_name='encounteraccessgrant',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('revoked_at__isnull', True), ('revoked_by__isnull', True)), models.Q(('revoked_at__isnull', False), ('revoked_by__isnull', False)), _connector='OR'), name='consult_grant_revoke_valid'),
        ),
        migrations.RunPython(
            populate_consultation_participants,
            migrations.RunPython.noop,
        ),
    ]
