# Generated by Django 5.2.16 on 2026-08-01 20:05

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinicians', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='환자 UUID')),
                ('medical_record_number', models.CharField(blank=True, help_text='병원에서 부여하는 환자번호입니다.', max_length=50, null=True, unique=True, verbose_name='병원 환자번호')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='환자 이름')),
                ('birth_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='생년월일')),
                ('sex', models.CharField(choices=[('M', '남성'), ('F', '여성'), ('UNKNOWN', '미상')], db_index=True, default='UNKNOWN', max_length=10, verbose_name='성별')),
                ('phone', models.CharField(blank=True, db_index=True, max_length=30, verbose_name='전화번호')),
                ('emergency_contact', models.CharField(blank=True, max_length=30, verbose_name='비상 연락처')),
                ('address', models.TextField(blank=True, verbose_name='주소')),
                ('status', models.CharField(choices=[('ACTIVE', '활성'), ('INACTIVE', '비활성'), ('MERGED', '다른 환자에 통합됨')], db_index=True, default='ACTIVE', max_length=20, verbose_name='환자 상태')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 일시')),
                ('merged_into', models.ForeignKey(blank=True, help_text='중복 등록된 환자를 실제 환자에게 통합할 때 사용합니다.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='merged_patients', to='patients.patient', verbose_name='통합 대상 환자')),
                ('user', models.OneToOneField(blank=True, help_text='환자 앱 로그인 계정과 연결합니다.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_profile', to=settings.AUTH_USER_MODEL, verbose_name='사용자 계정')),
            ],
            options={
                'verbose_name': '환자',
                'verbose_name_plural': '환자',
                'db_table': 'patients',
                'ordering': ['name', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProvisionalIdentity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='임시 신원 UUID')),
                ('temporary_number', models.CharField(db_index=True, help_text='예: TEMP-20260802-001', max_length=50, unique=True, verbose_name='임시 환자번호')),
                ('temporary_name', models.CharField(db_index=True, help_text='예: 신원미상-001', max_length=100, verbose_name='임시 표시 이름')),
                ('estimated_sex', models.CharField(choices=[('M', '남성 추정'), ('F', '여성 추정'), ('UNKNOWN', '미상')], default='UNKNOWN', max_length=10, verbose_name='추정 성별')),
                ('estimated_age', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(150)], verbose_name='추정 나이')),
                ('distinguishing_features', models.TextField(blank=True, help_text='의복, 외형, 소지품 등의 식별 정보를 기록합니다.', verbose_name='식별 특징')),
                ('status', models.CharField(choices=[('UNIDENTIFIED', '신원미상'), ('RESOLVED', '신원 확인 완료')], db_index=True, default='UNIDENTIFIED', max_length=20, verbose_name='신원 확인 상태')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='신원 확인 일시')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 일시')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_provisional_identities', to='clinicians.clinician', verbose_name='신원 확인 의료진')),
                ('resolved_patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resolved_provisional_identities', to='patients.patient', verbose_name='확인된 정식 환자')),
            ],
            options={
                'verbose_name': '신원미상 임시 신원',
                'verbose_name_plural': '신원미상 임시 신원',
                'db_table': 'provisional_identities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['name', 'birth_date'], name='patient_name_birth_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['status', 'name'], name='patient_status_name_idx'),
        ),
        migrations.AddConstraint(
            model_name='patient',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('merged_into__isnull', False), ('status', 'MERGED')), models.Q(('merged_into__isnull', True), ('status__in', ['ACTIVE', 'INACTIVE'])), _connector='OR'), name='patient_merged_target_valid'),
        ),
        migrations.AddIndex(
            model_name='provisionalidentity',
            index=models.Index(fields=['status', 'created_at'], name='provisional_status_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='provisionalidentity',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('resolved_at__isnull', True), ('resolved_patient__isnull', True), ('status', 'UNIDENTIFIED')), models.Q(('resolved_at__isnull', False), ('resolved_patient__isnull', False), ('status', 'RESOLVED')), _connector='OR'), name='provisional_resolution_valid'),
        ),
    ]
