# Generated by Django 5.2.16 on 2026-08-02 11:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientAccountClaim',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 일시')),
                ('claim_code_hash', models.CharField(help_text='일회용 연결 코드를 평문으로 저장하지 않고 Django 비밀번호 해시 형식으로 저장합니다.', max_length=128, unique=True, verbose_name='연결 코드 해시')),
                ('status', models.CharField(choices=[('ISSUED', '발급됨'), ('USED', '사용 완료'), ('EXPIRED', '만료됨'), ('REVOKED', '취소됨')], db_index=True, default='ISSUED', max_length=16, verbose_name='연결 요청 상태')),
                ('expires_at', models.DateTimeField(db_index=True, verbose_name='만료 일시')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='사용 완료 일시')),
                ('failed_attempts', models.PositiveSmallIntegerField(default=0, verbose_name='인증 실패 횟수')),
                ('claimed_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='patient_account_claim', to=settings.AUTH_USER_MODEL, verbose_name='연결된 모바일 사용자')),
                ('issued_by', models.ForeignKey(help_text='연결 코드를 발급한 관리자 또는 의료진 계정입니다.', on_delete=django.db.models.deletion.PROTECT, related_name='issued_patient_account_claims', to=settings.AUTH_USER_MODEL, verbose_name='발급 사용자')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='account_claims', to='patients.patient', verbose_name='연결 대상 환자')),
            ],
            options={
                'verbose_name': '환자 계정 연결 요청',
                'verbose_name_plural': '환자 계정 연결 요청',
                'db_table': 'patient_account_claims',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['patient', 'status', 'expires_at'], name='ptclaim_patient_status_idx'), models.Index(fields=['status', 'expires_at'], name='ptclaim_status_expire_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'ISSUED')), fields=('patient',), name='ptclaim_one_issued_uniq'), models.CheckConstraint(condition=models.Q(models.Q(('claimed_user__isnull', True), ('status', 'ISSUED'), ('used_at__isnull', True)), models.Q(('claimed_user__isnull', False), ('status', 'USED'), ('used_at__isnull', False)), models.Q(('claimed_user__isnull', True), ('status__in', ['EXPIRED', 'REVOKED']), ('used_at__isnull', True)), _connector='OR'), name='ptclaim_status_valid_chk')],
            },
        ),
    ]
