# Generated by Django 5.2.16 on 2026-08-02 15:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicians', '0001_initial'),
        ('patients', '0002_patientaccountclaim'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientIdentityResolutionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 일시')),
                ('provisional_identity_uuid', models.UUIDField(unique=True, verbose_name='삭제된 임시 신원 UUID')),
                ('temporary_number', models.CharField(db_index=True, max_length=50, verbose_name='임시 환자번호')),
                ('temporary_name', models.CharField(max_length=100, verbose_name='임시 표시 이름')),
                ('estimated_sex', models.CharField(blank=True, max_length=10, verbose_name='추정 성별 스냅샷')),
                ('estimated_age', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='추정 나이 스냅샷')),
                ('distinguishing_features', models.TextField(blank=True, verbose_name='식별 특징 스냅샷')),
                ('resolution_type', models.CharField(choices=[('EXISTING', '기존 환자 차트 병합'), ('NEW', '신규 환자 차트 생성')], db_index=True, max_length=16, verbose_name='신원확인 처리 유형')),
                ('resolved_at', models.DateTimeField(db_index=True, verbose_name='신원확인 처리 일시')),
                ('moved_encounter_ids', models.JSONField(blank=True, default=list, verbose_name='이관된 진료 UUID 목록')),
                ('moved_encounter_count', models.PositiveIntegerField(default=0, verbose_name='이관된 진료 건수')),
                ('deletion_snapshot', models.JSONField(blank=True, default=dict, help_text='PostgreSQL Trigger가 ProvisionalIdentity 삭제 직전에 기록합니다.', verbose_name='삭제 시점 원본 스냅샷')),
                ('provisional_deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='임시 신원 삭제 일시')),
                ('note', models.TextField(blank=True, verbose_name='처리 메모')),
                ('resolved_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='identity_resolution_logs', to='clinicians.clinician', verbose_name='신원확인 처리 의료진')),
                ('target_patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='identity_resolution_logs', to='patients.patient', verbose_name='연결된 정식 환자')),
            ],
            options={
                'verbose_name': '환자 신원확인 처리 로그',
                'verbose_name_plural': '환자 신원확인 처리 로그',
                'db_table': 'patient_identity_resolution_logs',
                'ordering': ['-resolved_at', '-created_at'],
                'indexes': [models.Index(fields=['target_patient', 'resolved_at'], name='ptidres_patient_date_idx'), models.Index(fields=['resolution_type', 'resolved_at'], name='ptidres_type_date_idx')],
            },
        ),
    ]
