# Generated by Django 5.2.16 on 2026-08-04 12:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0003_hospital_external_place_id_and_more'),
        ('patients', '0004_provisional_identity_chart_trigger'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 일시')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, db_index=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
            options={
                'db_table': 'guardians',
            },
        ),
        migrations.CreateModel(
            name='PatientPrivateIdentity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 일시')),
                ('global_patient_number', models.CharField(max_length=100, unique=True)),
                ('resident_registration_number_encrypted', models.TextField()),
                ('resident_registration_number_masked', models.CharField(max_length=20)),
                ('rrn_checksum_valid', models.BooleanField(default=False)),
                ('phone_encrypted', models.TextField(blank=True)),
                ('email_encrypted', models.TextField(blank=True)),
                ('encryption_key_version', models.CharField(default='v1', max_length=50)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='private_identity', to='patients.patient')),
            ],
            options={
                'db_table': 'patient_private',
            },
        ),
        migrations.CreateModel(
            name='PatientGuardian',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 일시')),
                ('relationship', models.CharField(max_length=50)),
                ('can_view_records', models.BooleanField(default=False)),
                ('can_book_appointments', models.BooleanField(default=False)),
                ('can_receive_notifications', models.BooleanField(default=False)),
                ('consent_status', models.CharField(default='pending', max_length=30)),
                ('guardian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_links', to='patients.guardian')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardian_links', to='patients.patient')),
            ],
            options={
                'db_table': 'patient_guardians',
                'constraints': [models.UniqueConstraint(fields=('patient', 'guardian'), name='uniq_patient_guardian')],
            },
        ),
        migrations.CreateModel(
            name='PatientHospitalIdentifier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 일시')),
                ('hospital_specific_mrn', models.CharField(max_length=100)),
                ('first_visit_date', models.DateField(blank=True, null=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('status', models.CharField(default='active', max_length=30)),
                ('source_system', models.CharField(blank=True, max_length=100)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patient_identifiers', to='hospitals.hospital')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_identifiers', to='patients.patient')),
            ],
            options={
                'db_table': 'patient_hospital_ids',
                'constraints': [models.UniqueConstraint(fields=('patient', 'hospital'), name='uniq_patient_hospital_id'), models.UniqueConstraint(fields=('hospital', 'hospital_specific_mrn'), name='uniq_hospital_specific_mrn'), models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('patient',), name='uniq_primary_hospital_per_patient')],
            },
        ),
    ]
