# Generated by Django 5.2.16 on 2026-08-04 02:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserConsent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 일시')),
                ('consent_type', models.CharField(choices=[('TERMS_OF_SERVICE', '서비스 이용약관'), ('PRIVACY', '개인정보 처리'), ('SENSITIVE_DATA', '민감정보 처리'), ('AI_ASSISTANCE', '의료 AI 안내'), ('MARKETING', '마케팅'), ('RESEARCH', '연구 활용')], db_index=True, max_length=24)),
                ('document_version', models.CharField(max_length=50)),
                ('agreed', models.BooleanField(default=False)),
                ('agreed_at', models.DateTimeField(blank=True, null=True)),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=24)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'consent_type', 'document_version'), name='userconsent_type_version_uniq'), models.CheckConstraint(condition=models.Q(('agreed', False), models.Q(('agreed', True), ('agreed_at__isnull', False)), _connector='OR'), name='userconsent_agreed_at_req'), models.CheckConstraint(condition=models.Q(('withdrawn_at__isnull', True), models.Q(('agreed_at__isnull', False), ('withdrawn_at__gte', models.F('agreed_at'))), _connector='OR'), name='userconsent_withdraw_valid')],
            },
        ),
    ]
