# Generated by Django 5.2.16 on 2026-07-31 18:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('PATIENT', 'Patient'), ('CLINICIAN', 'Clinician'), ('ADMIN', 'Administrator')], max_length=16),
        ),
    ]
