export const APPOINTMENT_DURATION_OPTIONS =
  [
    15,
    30,
    60,
  ] as const

export const DEFAULT_APPOINTMENT_DURATION_MINUTES =
  30

export const APPOINTMENT_CALENDAR_SLOT_MINUTES =
  15

export const APPOINTMENT_CALENDAR_START_HOUR =
  9

export const APPOINTMENT_CALENDAR_END_HOUR =
  18
