# Generated by Django 5.2.16 on 2026-08-01 21:18

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        ('clinical_records', '0001_initial'),
        ('clinicians', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 일시')),
                ('status', models.CharField(choices=[('DRAFT', '작성 중'), ('ACTIVE', '처방 중'), ('COMPLETED', '처방 완료'), ('DISCONTINUED', '중단'), ('CANCELLED', '취소')], db_index=True, default='DRAFT', max_length=20, verbose_name='처방 상태')),
                ('notes', models.TextField(blank=True, verbose_name='처방 참고사항')),
                ('prescribed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='처방 일시')),
                ('discontinued_at', models.DateTimeField(blank=True, null=True, verbose_name='중단 일시')),
                ('clinical_record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to='clinical_records.clinicalrecord', verbose_name='진료기록')),
                ('clinician', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to='clinicians.clinician', verbose_name='처방 의료진')),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to='appointments.encounter', verbose_name='진료 건')),
            ],
            options={
                'verbose_name': '처방전',
                'verbose_name_plural': '처방전',
                'ordering': ['-prescribed_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrescriptionItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 일시')),
                ('medicine_name', models.CharField(db_index=True, max_length=200, verbose_name='약품명')),
                ('dosage', models.DecimalField(decimal_places=4, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))], verbose_name='1회 투여량')),
                ('dose_unit', models.CharField(help_text='예: mg, mL, 정, 캡슐', max_length=30, verbose_name='투여 단위')),
                ('frequency', models.CharField(help_text='예: 1일 3회, BID, TID', max_length=100, verbose_name='복용 빈도')),
                ('route', models.CharField(blank=True, help_text='예: 경구, 정맥, 근육, 피하', max_length=50, verbose_name='투여 경로')),
                ('instructions', models.TextField(blank=True, verbose_name='복약 지시')),
                ('start_date', models.DateField(verbose_name='복용 시작일')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='복용 종료일')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='prescriptions.prescription', verbose_name='처방전')),
            ],
            options={
                'verbose_name': '처방 약품',
                'verbose_name_plural': '처방 약품',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['encounter', 'prescribed_at'], name='presc_encounter_date_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['clinician', 'prescribed_at'], name='presc_clinician_date_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['status', 'prescribed_at'], name='presc_status_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='prescription',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'DISCONTINUED'), _negated=True), ('discontinued_at__isnull', False), _connector='OR'), name='prescription_discontinued_at_required'),
        ),
        migrations.AddIndex(
            model_name='prescriptionitem',
            index=models.Index(fields=['prescription', 'created_at'], name='prescitem_presc_idx'),
        ),
        migrations.AddIndex(
            model_name='prescriptionitem',
            index=models.Index(fields=['medicine_name'], name='prescitem_medicine_idx'),
        ),
        migrations.AddConstraint(
            model_name='prescriptionitem',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='prescriptionitem_end_after_start'),
        ),
    ]
