# Generated by Django 5.2.16 on 2026-08-04 12:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrugMaster',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 일시')),
                ('drug_code', models.CharField(max_length=100, unique=True)),
                ('product_name', models.CharField(max_length=255)),
                ('ingredient', models.TextField()),
                ('strength', models.CharField(blank=True, max_length=100)),
                ('route', models.CharField(blank=True, max_length=100)),
                ('dose_example', models.TextField(blank=True)),
                ('frequency_example', models.CharField(blank=True, max_length=100)),
                ('timing_example', models.CharField(blank=True, max_length=255)),
                ('stroke_related_use_and_caution', models.TextField(blank=True)),
                ('source_url', models.URLField(blank=True, max_length=500)),
                ('clinical_disclaimer', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'drug_master',
            },
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='drug',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prescription_items', to='prescriptions.drugmaster'),
        ),
    ]
