# Generated by Django 5.2.16 on 2026-08-03 07:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatConversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 일시')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='대화 제목')),
                ('status', models.CharField(choices=[('ACTIVE', '진행 중'), ('ARCHIVED', '보관')], db_index=True, default='ACTIVE', max_length=16, verbose_name='상태')),
                ('last_message_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='마지막 메시지 일시')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='모델 설정이나 대화 컨텍스트 식별자를 저장합니다.', verbose_name='추가 정보')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chat_conversations', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '챗봇 대화',
                'verbose_name_plural': '챗봇 대화',
                'ordering': ['-last_message_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 일시')),
                ('role', models.CharField(choices=[('USER', '사용자'), ('ASSISTANT', 'AI'), ('SYSTEM', '시스템'), ('TOOL', '도구')], db_index=True, max_length=16, verbose_name='발신 역할')),
                ('sequence', models.PositiveIntegerField(verbose_name='메시지 순서')),
                ('idempotency_key', models.CharField(blank=True, help_text='클라이언트 또는 Genkit 요청의 고유 키를 저장합니다.', max_length=100, null=True, verbose_name='중복 방지 키')),
                ('content', models.TextField(blank=True, verbose_name='메시지 내용')),
                ('model_name', models.CharField(blank=True, max_length=100, verbose_name='AI 모델명')),
                ('tool_name', models.CharField(blank=True, max_length=100, verbose_name='도구명')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='도구 호출 인자, 결과 요약, 토큰 사용량 등을 저장합니다.', verbose_name='추가 정보')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chatbot.chatconversation', verbose_name='대화')),
            ],
            options={
                'verbose_name': '챗봇 메시지',
                'verbose_name_plural': '챗봇 메시지',
                'ordering': ['sequence'],
            },
        ),
        migrations.AddIndex(
            model_name='chatconversation',
            index=models.Index(fields=['user', 'status', 'updated_at'], name='chat_conv_user_status_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['conversation', 'sequence'], name='chat_msg_conv_seq_idx'),
        ),
        migrations.AddConstraint(
            model_name='chatmessage',
            constraint=models.UniqueConstraint(fields=('conversation', 'sequence'), name='chat_msg_conv_seq_unique'),
        ),
        migrations.AddConstraint(
            model_name='chatmessage',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key__isnull', False), models.Q(('idempotency_key', ''), _negated=True)), fields=('conversation', 'idempotency_key'), name='chat_msg_idempotency_unique'),
        ),
        migrations.AddConstraint(
            model_name='chatmessage',
            constraint=models.CheckConstraint(condition=models.Q(('sequence__gte', 1)), name='chat_msg_sequence_positive'),
        ),
        migrations.AddConstraint(
            model_name='chatmessage',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('role', 'USER'), _negated=True), models.Q(('content', ''), _negated=True), _connector='OR'), name='chat_user_content_required'),
        ),
        migrations.AddConstraint(
            model_name='chatmessage',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('role', 'TOOL'), _negated=True), models.Q(('tool_name', ''), _negated=True), _connector='OR'), name='chat_tool_name_required'),
        ),
    ]
