# Generated by Django 5.2.16 on 2026-08-04 02:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
        ('chatbot', '0002_chatfeedback_chattoolexecution_knowledgechunk_and_more'),
        ('ct_analysis', '0002_aimodelversion_inferenceartifact_inferencefinding_and_more'),
        ('imaging', '0001_initial'),
        ('patients', '0004_provisional_identity_chart_trigger'),
        ('test_results', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatcontextreference',
            name='imaging_study',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='chat_context_references', to='imaging.imagingstudy'),
        ),
        migrations.AddField(
            model_name='chatcontextreference',
            name='inference_result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='chat_context_references', to='ct_analysis.inferenceresult'),
        ),
        migrations.AddField(
            model_name='chatcontextreference',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='context_references', to='chatbot.chatmessage'),
        ),
        migrations.AddField(
            model_name='chatcontextreference',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='chat_context_references', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='chatcontextreference',
            name='test_result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='chat_context_references', to='test_results.testresult'),
        ),
        migrations.AddField(
            model_name='chatfeedback',
            name='message',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='chatbot.chatmessage'),
        ),
        migrations.AddField(
            model_name='chatfeedback',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chat_feedback', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chattoolexecution',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_executions', to='chatbot.chatconversation'),
        ),
        migrations.AddField(
            model_name='chattoolexecution',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tool_executions', to='chatbot.chatmessage'),
        ),
        migrations.AddField(
            model_name='knowledgedocument',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_knowledge_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='knowledgedocument',
            name='stored_object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='knowledge_documents', to='assets.storedobject'),
        ),
        migrations.AddField(
            model_name='knowledgechunk',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='chatbot.knowledgedocument'),
        ),
        migrations.AddField(
            model_name='knowledgeembedding',
            name='chunk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embeddings', to='chatbot.knowledgechunk'),
        ),
        migrations.AddIndex(
            model_name='chatcontextreference',
            index=models.Index(fields=['conversation', 'created_at'], name='chatctx_conv_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='chatcontextreference',
            constraint=models.CheckConstraint(condition=models.Q(('patient__isnull', False), ('encounter__isnull', False), ('imaging_study__isnull', False), ('inference_result__isnull', False), ('test_result__isnull', False), _connector='OR'), name='chatctx_reference_required'),
        ),
        migrations.AddIndex(
            model_name='chattoolexecution',
            index=models.Index(fields=['conversation', 'status'], name='chattool_conv_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='chattoolexecution',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key__isnull', False), models.Q(('idempotency_key', ''), _negated=True)), fields=('conversation', 'idempotency_key'), name='chattool_conv_idem_uniq'),
        ),
        migrations.AddConstraint(
            model_name='chattoolexecution',
            constraint=models.CheckConstraint(condition=models.Q(('started_at__isnull', True), ('completed_at__isnull', True), ('completed_at__gte', models.F('started_at')), _connector='OR'), name='chattool_timestamps_valid'),
        ),
        migrations.AddConstraint(
            model_name='knowledgedocument',
            constraint=models.CheckConstraint(condition=models.Q(('stored_object__isnull', False), models.Q(('source_uri', ''), _negated=True), _connector='OR'), name='knowledge_doc_source_req'),
        ),
        migrations.AddConstraint(
            model_name='knowledgechunk',
            constraint=models.UniqueConstraint(fields=('document', 'sequence'), name='knowledge_chunk_seq_uniq'),
        ),
        migrations.AddConstraint(
            model_name='knowledgeembedding',
            constraint=models.UniqueConstraint(fields=('chunk', 'provider', 'model_name'), name='knowledge_embedding_uniq'),
        ),
    ]
