# Generated by Django 5.2.16 on 2026-08-04 02:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        ('ct_analysis', '0002_aimodelversion_inferenceartifact_inferencefinding_and_more'),
        ('diagnostics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagingStudy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 일시')),
                ('modality', models.CharField(choices=[('CT', 'CT'), ('MR', 'MRI'), ('CR', 'X-ray'), ('US', '초음파'), ('PT', 'PET'), ('NM', '핵의학'), ('OTHER', '기타')], db_index=True, max_length=16)),
                ('study_instance_uid', models.CharField(max_length=128)),
                ('study_description', models.CharField(blank=True, max_length=255)),
                ('body_part', models.CharField(blank=True, max_length=100)),
                ('referring_clinician_name', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('IMPORTING', '가져오는 중'), ('VALIDATING', '검증 중'), ('READY', '사용 가능'), ('FAILED', '실패'), ('ARCHIVED', '보관')], db_index=True, default='IMPORTING', max_length=16)),
                ('imported_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('examination', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='imaging_study', to='diagnostics.examination')),
                ('imported_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='imported_imaging_studies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-examination__performed_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImagingSeries',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 일시')),
                ('series_instance_uid', models.CharField(max_length=128)),
                ('series_number', models.IntegerField(blank=True, null=True)),
                ('modality', models.CharField(choices=[('CT', 'CT'), ('MR', 'MRI'), ('CR', 'X-ray'), ('US', '초음파'), ('PT', 'PET'), ('NM', '핵의학'), ('OTHER', '기타')], max_length=16)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('body_part', models.CharField(blank=True, max_length=100)),
                ('instance_count', models.PositiveIntegerField(default=0)),
                ('rows', models.PositiveIntegerField(blank=True, null=True)),
                ('columns', models.PositiveIntegerField(blank=True, null=True)),
                ('slice_thickness', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series', to='imaging.imagingstudy')),
            ],
            options={
                'ordering': ['series_number', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImagingAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 일시')),
                ('asset_type', models.CharField(choices=[('ORIGINAL_DICOM', 'DICOM 원본'), ('DICOM_MANIFEST', 'DICOM Manifest'), ('NIFTI_VOLUME', 'NIfTI 볼륨'), ('NRRD_VOLUME', 'NRRD 볼륨'), ('THUMBNAIL', '썸네일'), ('PREVIEW', '미리보기'), ('OTHER', '기타')], db_index=True, max_length=24)),
                ('is_primary', models.BooleanField(db_index=True, default=False)),
                ('conversion_status', models.CharField(choices=[('NOT_REQUIRED', '변환 불필요'), ('PENDING', '변환 대기'), ('PROCESSING', '변환 중'), ('COMPLETED', '변환 완료'), ('FAILED', '변환 실패')], db_index=True, default='NOT_REQUIRED', max_length=16)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('stored_object', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='imaging_asset', to='assets.storedobject')),
                ('series', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='imaging.imagingseries')),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='imaging.imagingstudy')),
            ],
            options={
                'ordering': ['asset_type', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImagingAnnotation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 일시')),
                ('annotation_type', models.CharField(choices=[('SEGMENTATION', '분할 마스크'), ('ROI', '관심 영역'), ('DRAWING', '그리기'), ('MEASUREMENT', '측정')], max_length=24)),
                ('version', models.PositiveIntegerField(default=1)),
                ('label', models.CharField(blank=True, max_length=100)),
                ('is_final', models.BooleanField(db_index=True, default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_imaging_annotations', to=settings.AUTH_USER_MODEL)),
                ('inference_result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='annotations', to='ct_analysis.inferenceresult')),
                ('parent_annotation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='imaging.imagingannotation')),
                ('stored_object', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='imaging_annotation', to='assets.storedobject')),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='annotations', to='imaging.imagingstudy')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='imagingstudy',
            index=models.Index(fields=['modality', 'status'], name='imgstudy_modality_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='imagingstudy',
            constraint=models.UniqueConstraint(fields=('study_instance_uid',), name='imagingstudy_uid_uniq'),
        ),
        migrations.AddIndex(
            model_name='imagingseries',
            index=models.Index(fields=['study', 'series_number'], name='imgseries_study_num_idx'),
        ),
        migrations.AddConstraint(
            model_name='imagingseries',
            constraint=models.UniqueConstraint(fields=('study', 'series_instance_uid'), name='imgseries_study_uid_uniq'),
        ),
        migrations.AddIndex(
            model_name='imagingasset',
            index=models.Index(fields=['study', 'asset_type'], name='imgasset_study_type_idx'),
        ),
        migrations.AddConstraint(
            model_name='imagingasset',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('study', 'asset_type'), name='imgasset_primary_type_uniq'),
        ),
        migrations.AddConstraint(
            model_name='imagingannotation',
            constraint=models.UniqueConstraint(fields=('study', 'annotation_type', 'label', 'version'), name='imgannotation_version_uniq'),
        ),
    ]
